import logging
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib import colors

log = logging.getLogger(__name__)


def generate_report(topic: str, articles: list, output_dir: str = "reports") -> str:
    """Generate a structured PDF research report from summarised articles."""
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{output_dir}/research_{timestamp}.pdf"

    doc = SimpleDocTemplate(
        filename, pagesize=A4,
        leftMargin=20*2.835, rightMargin=20*2.835,
        topMargin=20*2.835, bottomMargin=20*2.835
    )

    title_style = ParagraphStyle(
        "title", fontSize=18, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1F4E79"), spaceAfter=10
    )
    heading_style = ParagraphStyle(
        "heading", fontSize=12, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#2E75B6"),
        spaceBefore=12, spaceAfter=4
    )
    body_style = ParagraphStyle(
        "body", fontSize=9, fontName="Helvetica",
        textColor=colors.HexColor("#595959"),
        leading=14, spaceAfter=6, alignment=TA_JUSTIFY
    )
    url_style = ParagraphStyle(
        "url", fontSize=8, fontName="Helvetica",
        textColor=colors.HexColor("#2E75B6"), spaceAfter=8
    )
    meta_style = ParagraphStyle(
        "meta", fontSize=8, fontName="Helvetica",
        textColor=colors.gray, spaceAfter=12
    )

    story = []
    story.append(Paragraph(f"Research Report: {topic}", title_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')} | Sources: {len(articles)} articles",
        meta_style
    ))
    story.append(HRFlowable(width="100%", thickness=1,
                             color=colors.HexColor("#2E75B6"), spaceAfter=12))
    story.append(Paragraph("Key Findings", heading_style))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.lightgrey, spaceAfter=8))

    for i, article in enumerate(articles, 1):
        story.append(Paragraph(f"{i}. {article['title']}", heading_style))
        story.append(Paragraph(article["summary"], body_style))
        story.append(Paragraph(f"Source: {article['url']}", url_style))

    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.lightgrey, spaceAfter=8))
    story.append(Paragraph(
        "Generated by AI Research Assistant Agent | github.com/Gopikrishna1547",
        meta_style
    ))

    doc.build(story)
    log.info(f"Report saved to: {filename}")
    return filename
